# Generated by Django 6.1 on 2026-08-25 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=300, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'École',
                'verbose_name_plural': 'Écoles',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('PRIMAIRE', 'Primaire'), ('SECONDAIRE', 'Secondaire'), ('MATERNELLE', 'Maternelle')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom_complet', models.CharField(db_index=True, max_length=200)),
                ('option', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone_parent', models.CharField(blank=True, max_length=20, null=True)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='gestion.classe')),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='gestion.ecole')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='gestion.section')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=200)),
                ('annee_scolaire', models.CharField(max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_montant', models.CharField(choices=[('FC', 'FC'), ('USD', 'USD')], default='FC', max_length=3)),
                ('statut', models.CharField(choices=[('VALIDE', '✅ Valide'), ('INVALIDE', '❌ Invalide'), ('ANNULE', '⛔ Annulé')], default='INVALIDE', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('mois_paye', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], help_text='Mois où le paiement a été effectué')),
                ('mois_concerne', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], help_text='Mois pour lequel le paiement est effectué')),
                ('annee_paye', models.IntegerField(default=2026, help_text='Année où le paiement a été effectué')),
                ('annee_concerne', models.IntegerField(default=2026, help_text='Année pour laquelle le paiement est effectué')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('annule_at', models.DateTimeField(blank=True, null=True)),
                ('raison_annulation', models.TextField(blank=True, null=True)),
                ('historique_modifications', models.JSONField(blank=True, default=list)),
                ('annule_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_annules', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_crees', to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='gestion.ecole')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='gestion.eleve')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_modifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='gestion.section'),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('section', 'nom')},
        ),
    ]
