# Generated by Django 6.1 on 2026-09-19 08:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('FOURNITURES', 'Achat fournitures'), ('ELECTRICITE', 'Électricité'), ('EAU', 'Eau'), ('LOYER', 'Loyer'), ('SALAIRES', 'Salaires'), ('REPARATION', 'Réparation'), ('TRANSPORT', 'Transport'), ('FRAIS_ADMIN', 'Frais administratifs'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_montant', models.CharField(choices=[('FC', 'FC'), ('USD', 'USD')], default='USD', max_length=3)),
                ('date_sortie', models.DateField(default=datetime.datetime.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('VALIDE', '✅ Valide'), ('ANNULE', '⛔ Annulé')], default='VALIDE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('annule_at', models.DateTimeField(blank=True, null=True)),
                ('raison_annulation', models.TextField(blank=True, null=True)),
                ('annule_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties_annulees', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties_creees', to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sorties', to='gestion.ecole')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorties_modifiees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sortie',
                'verbose_name_plural': 'Sorties',
                'ordering': ['-date_sortie', '-created_at'],
            },
        ),
    ]
